config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container border shadow mt-4">
  <h1 class="text d-flex justify-content-center">Add a Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: @movies, prompt: 'Choose a movie' %>
    <%= f.input :comment %>
    <%= f.submit class:"btn btn-success"%>
  <% end %>
  <%= link_to "Back to list", list_path(@list), class:"btn btn-warning my-2"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%= console %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container border shadow m-4">
  <h1 class="text d-flex justify-content-center">Genders</h1>
    <ul>
        <% @lists.each do |list| %>
      <li>
        <%= link_to list.name, list_path(list) %>
      </li>
      <% end %>
    </ul>
  <%= link_to "Create a new gender", new_list_path, class: "btn btn-primary my-2" %>
</div>

app/views/lists/new.html.erb
<div class="container border shadow mt-4">
  <h1 class="text d-flex justify-content-center">Create a new list</h1>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit class: 'btn btn-success' %>
  <% end %>

  <%= link_to 'Back to all lists', lists_path, class: 'btn btn-warning mt-2 my-2' %>
</div>

app/views/lists/show.html.erb
<div class="container border shadow mt-4">
  <h1 class="text d-flex justify-content-center"><%= @list.name %></h1>

  <ul>
    <% @list.movies.each do |movie| %>
    <li>
    <%= movie.rating %>
    <%= movie.title %>
    </li>
    <% end %>
  </ul>
<%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, prompt: 'Choose a movie' %>
    <%= f.input :comment %>
    <%= f.submit class:"btn btn-success"%>
  <% end %>
  <%= link_to 'Back to the list', lists_path, class: 'btn btn-warning my-3' %>

</div>